export const AppsIcon = ({ className }: { className?: string }) => {
  return (
    <svg
      width="18"
      height="18"
      viewBox="0 0 18 18"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
    >
      <rect
        x="11"
        y="1"
        width="6"
        height="6"
        rx="2"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="11"
        y="11"
        width="6"
        height="6"
        rx="2"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="1"
        y="11"
        width="6"
        height="6"
        rx="2"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="1"
        y="1"
        width="6"
        height="6"
        rx="2"
        stroke="currentColor"
        strokeWidth="2"
      />
    </svg>
  );
};
